# Generated by Django 2.0.3 on 2018-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('car', models.CharField(max_length=200)),
                ('entry_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Peoples_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('category_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mustangroundup.Car')),
            ],
        ),
    ]
