# Generated by Django 5.2.14 on 2026-06-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
