# Generated by Django 2.0.3 on 2018-03-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0005_category_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best_of_show',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='peoples_choice',
            name='car_id',
        ),
        migrations.DeleteModel(
            name='Best_of_show',
        ),
        migrations.DeleteModel(
            name='Peoples_choice',
        ),
    ]
