# Generated by Django 2.0.3 on 2018-03-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0006_auto_20180311_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votes',
            options={'ordering': ('votes',)},
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='category_id',
            new_name='category',
        ),
    ]
