# Generated by Django 2.0.3 on 2018-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0007_auto_20180311_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Poll',
        ),
    ]
