# Generated by Django 2.0.3 on 2018-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0009_auto_20180401_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='entry_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
