# Generated by Django 2.0.3 on 2018-05-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustangroundup', '0010_auto_20180507_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
